### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by smillier** [docbender/ILI9341_openHAB#1]
Hi,

I would like to use your dev as a base for my installation but I can't compile, I'm missing buttons.h and arial.h. Where does it come from ?

regards

**Comment by docbender** [comment]
Hi, 
this project uses the forked library ILI9341_t3. The modified library is in separate branch. You can find it at: https://github.com/docbender/ILI9341_t3/tree/ESP  Part of this are these two files

**Comment by smillier** [comment]
Nice ! Thanks for your answer and for the work done.

**Comment by smillier** [comment]
Hi,

Have you tested the simplebinary binding with OpenHab 2 ?

**Comment by docbender** [comment]
I tested it with OH2 when OH2 was in beta stage. I run it still at 1.8.3 version

**Comment by smillier** [comment]
I'm having trouble to map openhab items to the display, do you have an
example of your openhab items file to display temperatures on the screen ?

**Comment by docbender** [comment]
I write it here. Maybe it would be useful for someone else.
Panel in this configuration has ID=2 and uses 26 items. Here is OH configuration for some of my items:

    Number lcdFreeRAM "Free RAM [%d B]" { simplebinary="tcpserver:2:0:dword:I" }
    Number lcdUptime "Uptime [%d s]" { simplebinary="tcpserver:2:1:dword:I" }
    Number lcdCpuVoltage  "Voltage CPU [%.2f V]" (grLcd) { simplebinary="tcpserver:2:2:float:I" }
    Number lcdTimeSet  "Time [%d]" (grLcd) { simplebinary="tcpserver:2:16:dword:O" }
    Number outdoorTemp  "Temperature [%.1f °C]" <temperature> (grChartOutdoorTemp) { simplebinary="port:2:1:float:I", simplebinary="tcpserver:2:7:float:O" }
    Number outdoorTempMin  "Minimal temperature [%.1f °C]" <temperature> (grChartOutdoorTemp)  { simplebinary="tcpserver:2:8:float:O" }
    Number outdoorTempMax  "Maximal temperature [%.1f °C]" <temperature> (grChartOutdoorTemp)  { simplebinary="tcpserver:2:9:float:O" }
    Number RGBW02Off  "Turn off library library" <none>  { simplebinary="tcpserver:2:12:byte" }
    Number RGBW03Off  "Turn off edge light" <none>  { simplebinary="tcpserver:2:14:byte" }
    Number RadioCmd  "Radio" <none>  { simplebinary="tcpserver:2:15:byte" }
    Number  lcdState "State [%s]"  (rs485)  { simplebinary="tcpserver:2:info:state" }
    Number  lcdPrevState "Previous state [%s]" (rs485)  { simplebinary="tcpserver:2:info:previous_state" }
    DateTime lcdChangetime "State changed [%1$tA, %1$td.%1$tm.%1$tY %1$tT] "  (rs485)  { simplebinary="tcpserver:2:info:state_change_time" }
    Number  lcdPacketLost "Packet lost [%.1f %%]"  { simplebinary="tcpserver:2:info:packet_lost" }

Data Item address specification just follows this rule:

    simplebinary="port name:device address:item address:[used data type]:[direction]"

**Comment by smillier** [comment]
Thanks, that's close to the config I've done for the items. Then you have some rules to update the outdoorTemp value on a schedule, right ? Can you provide an example of the temperature value update ?

**Comment by docbender** [comment]
OutdoorTemp is in my case fed by another device ( OpenHAB allows setup more devices to one item). 
By rule minimal and maximal values are evaluated. For that I use this python script (it takes historical data from database):

```python
from java.util import Calendar, Date

class outdoorTempRule(Rule):
    def __init__(self):
        self.logger = oh.getLogger("outdoorTempRule")

    def getEventTrigger(self):
        return [
            UpdatedEventTrigger("outdoorTemp")
        ]

    def execute(self, event):
        Min = pe.minimumSince(event.item, DateTime.now().minusDays(1), "dynamodb")
        MinTime = Calendar.getInstance()
        MinTime.time = Min.timestamp

        oh.postUpdate("outdoorTempMin", str(float(str(Min.state))))
        oh.postUpdate("outdoorTempMinTime", str(DateTimeType(MinTime)))

        Max = pe.maximumSince(event.item, DateTime.now().minusDays(1), "dynamodb")
        MaxTime = Calendar.getInstance()
        MaxTime.time = Max.timestamp

        oh.postUpdate("outdoorTempMax", str(Max.state))
        oh.postUpdate("outdoorTempMaxTime", str(DateTimeType(MaxTime)))

def getRules():
    return RuleSet([
        outdoorTempRule()
    ])
```

**Comment by smillier** [comment]
Perfect, I finally have it working. For a reason i ignore, my openhab wasn't starting the simplebinary binding and I couldn't see any values on the LCD. Now it's ok. Your binding works fine with OH 2.2.0.
Great work. Thanks.
